version: "3.5"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - chemotion_db:/var/lib/postgresql/data/
    networks:
      - chemotion

  msconvert:
    image: ptrxyz/chemotion:msconvert-1.1.2p220401
    restart: unless-stopped
    hostname: msconvert
    volumes:
      - spectra:/shared:rw
    networks:
      - chemotion

  spectra:
    image: ptrxyz/chemotion:spectra-1.1.2p220401
    restart: unless-stopped
    hostname: spectra
    volumes:
      - spectra:/shared:rw
    depends_on:
      - msconvert
    networks:
      - chemotion

  worker:
    image: ptrxyz/chemotion:eln-1.1.2p220401
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=worker
    depends_on:
      - db
      - eln
      - spectra
    volumes:
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    networks:
      - chemotion

  eln:
    image: ptrxyz/chemotion:eln-1.1.2p220401
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=eln
    depends_on:
      - db
      - spectra
    volumes:
      - ./shared/pullin:/shared
      - ./shared/backup:/backup
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    ports:
      - 4000:4000
    networks:
      - chemotion

volumes:
  chemotion:
    name: chemotion_app
  chemotion_data:
    name: chemotion_data
  chemotion_db:
    name: chemotion_db
  spectra:
    name: chemotion_spectra

networks:
  chemotion:
