production:
  :docserver:
    :enable: false
    :uri: <%= ENV['OFFICE_URL'] || 'https://610.onlyoffice.hydrogen.scc.kit.edu/' %>
    :api: web-apps/apps/api/documents/api.js
    :callback_server: <%= ENV['PUBLIC_URL'] %>
    :ext:
      :text:
        - doc
        - docx
      :spreadsheet:
        - xls
        - xlsx
      :presentation:
        - ppt
        - pptx
  :info:
    :address: Fritz-Haber-Weg 6, Geb. 30.42 76131 Karlsruhe Germany
    :title: Complat ELN
    :name: Complat ELN
    :logo: https://www.chemotion.net/images/repo/chemotion_full.svg
    :mail: chemotion@ioc.kit.edu
    :website: www.chemotion.net
    :feedbackurl: ''
