name: Release Chemotion CLI

on:
  push:
    tags:
      - "*"

jobs:
  build-release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true
      - name: Build Go for all OSes
        run: |
          cd  chemotion-cli
          go  mod          verify
          GOOS=linux   GOARCH=amd64 go  build -o chemotion
          GOOS=darwin  GOARCH=arm64 go  build -o chemotion.arm.osx
          GOOS=darwin  GOARCH=amd64 go  build -o chemotion.amd.osx
          GOOS=windows GOARCH=amd64 go  build -o chemotion.exe
          mv  chemotion ..
          mv  chemotion.arm.osx ..
          mv  chemotion.amd.osx ..
          mv  chemotion.exe ..
      - name: Release Binaries
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            chemotion
            chemotion.arm.osx
            chemotion.amd.osx
            chemotion.exe
            docker-compose.yml
